# WordPressDev, Copyright 2019 Google LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

name: wordpressdev

recipe: wordpress

config:
  php: '7.4'
  via: nginx
  webroot: public
  database: mariadb
  xdebug: false # This needs to be false initially because otherwise provisioning takes much longer.
  config:
    php: php.ini

env_file:
  - .env.base
  - .env

proxy:
  appserver_nginx:
    - wordpressdev.lndo.site
    - "*.wordpressdev.lndo.site"

services:
  appserver:
    overrides:
      environment:
        # Support debugging with XDEBUG.
        PHP_IDE_CONFIG: "serverName=wordpressdev.lndo.site"
    composer:
      # Note installing phpunit should be temporary because core should really install it via composer on its own.
      phpunit/phpunit: "^6"
    install_dependencies_as_root:
      - bash bin/install-dependencies.sh
      # Allow loopback requests to work.
      - echo "127.0.0.1  wordpressdev.lndo.site" >> /etc/hosts
    run:
      - bash bin/setup-wordpress.sh
    run_as_root:
      - bash /app/bin/xdebug-resume.sh

tooling:
  npm:
    service: appserver
  npx:
    service: appserver
  yarn:
    service: appserver
  grunt:
    service: appserver
    cmd: "npx grunt"
  gulp:
    service: appserver
    cmd: "npx gulp"
  composer:
    service: appserver
  git:
    service: appserver
  svn:
    service: appserver
  phpunit:
    service: appserver
  log:
    service: appserver
    cmd: bash /app/bin/tail-php-error-log.sh
  wp:
    service: appserver
  xdebug-on:
    service: appserver
    description: Enable Xdebug for nginx.
    cmd: bash /app/bin/xdebug-on.sh
    user: root
  xdebug-off:
    service: appserver
    description: Disable Xdebug for nginx.
    cmd: bash /app/bin/xdebug-off.sh
    user: root
