name: wordpressdev

recipe: wordpress

config:
  php: '7.2'
  via: nginx
  webroot: public
  database: mariadb
  xdebug: false

  conf:
    server: config/wordpress.conf

services:
  appserver:
    composer:
      # Note installing phpunit should be temporary because core should really install it via composer on its own.
      phpunit/phpunit: "^6"
    install_dependencies_as_root:
      - apt-get update -y
      - apt-get install gnupg -y
      - curl -sL https://deb.nodesource.com/setup_10.x | bash -
      - apt-get install nodejs -y
      - apt-get install zip -y
      - apt-get install subversion -y
      # Allow loopback requests to work.
      - echo "127.0.0.1  wordpressdev.lando.site" >> /etc/hosts
    install_dependencies_as_me:
      # Setup environment variables.
      - if [ ! -e $LANDO_MOUNT/.env ]; then cp $LANDO_MOUNT/config/.env $LANDO_MOUNT/.env && sed -i "s#/app#$LANDO_MOUNT#" $LANDO_MOUNT/.env; fi
    run:
      # Setup WordPress for contributing via git.
      - if [ ! -e $LANDO_MOUNT/public/trunk-git ]; then git clone --depth 1 https://github.com/WordPress/wordpress-develop.git $LANDO_MOUNT/public/trunk-git; fi
      - if [ ! -e $LANDO_MOUNT/public/trunk-git/wp-config.php ]; then cp $LANDO_MOUNT/config/wp-config.php $LANDO_MOUNT/public/trunk-git/wp-config.php; fi
      - if [ ! -e $LANDO_MOUNT/public/trunk-git/wp-tests-config.php ]; then cp $LANDO_MOUNT/config/wp-tests-config.php $LANDO_MOUNT/public/trunk-git/wp-tests-config.php; fi
      - cd $LANDO_MOUNT/public/trunk-git && composer install
      - cd $LANDO_MOUNT/public/trunk-git; npm install && npx grunt
      # Setup WordPress for contributing via SVN.
      - if [ ! -e $LANDO_MOUNT/public/trunk-svn ]; then svn co https://develop.svn.wordpress.org/trunk/ $LANDO_MOUNT/public/trunk-svn; fi
      - if [ ! -e $LANDO_MOUNT/public/trunk-svn/wp-config.php ]; then cp $LANDO_MOUNT/config/wp-config.php $LANDO_MOUNT/public/trunk-svn/wp-config.php; fi
      - if [ ! -e $LANDO_MOUNT/public/trunk-svn/wp-tests-config.php ]; then cp $LANDO_MOUNT/config/wp-tests-config.php $LANDO_MOUNT/public/trunk-svn/wp-tests-config.php; fi
      - cd $LANDO_MOUNT/public/trunk-svn && composer install
      - cd $LANDO_MOUNT/public/trunk-svn; npm install && npx grunt
      # Install WordPress (for both variants).
      - if ! wp core is-installed; then wp core install --url="https://$LANDO_APP_NAME.$LANDO_DOMAIN/" --title="WordPress Develop" --admin_name="admin" --admin_email="admin@local.test" --admin_password="password"; fi

tooling:
  npm:
    service: appserver
  grunt:
    service: appserver
    cmd: "npx grunt"
  gulp:
    service: appserver
    cmd: "npx gulp"
  composer:
    service: appserver
  git:
    service: appserver
  svn:
    service: appserver
  phpunit:
    service: appserver
  wp:
    service: appserver
