<?php // DO NOT EDIT THIS FILE! Please put customizations in the git-ignored wp-config-local.php!
/**
 * WordPress configuration file.
 *
 * @copyright 2019 Google LLC
 * @license   GNU General Public License, version 2
 * @link      https://github.com/GoogleChromeLabs/wordpressdev
 */

// Allow local environment to override config.
if ( file_exists( dirname( __FILE__ ) . '/wp-config-local.php' ) ) {
	require dirname( __FILE__ ) . '/wp-config-local.php';
} elseif ( file_exists( dirname( dirname( __FILE__ ) ) . '/wp-config-local.php' ) ) {
	require dirname( dirname( __FILE__ ) ) . '/wp-config-local.php';
}

// Load custom functions.
if ( ! function_exists( '_wordpressdev_set_directory_constants' ) ) {
	require_once dirname( __FILE__ ) . '/functions.php';
}

// Detect and set WordPress core and content locations.
if ( ! defined( 'WP_CORE_PATH_RELATIVE' ) ) {
	_wordpressdev_set_directory_constants();
}

/**
 * WordPress Database Table prefix.
 *
 * You can have multiple installations in one database if you give each
 * a unique prefix. Only numbers, letters, and underscores please!
 */
$table_prefix = 'wp_';

// Define constants that haven't been overridden by wp-tests-config-local.php.
$constants = array(
	'DB_NAME'                        => 'wordpress',
	'DB_USER'                        => 'wordpress',
	'DB_PASSWORD'                    => 'wordpress',
	'DB_HOST'                        => 'database:3306',
	'DB_CHARSET'                     => 'utf8',
	'DB_COLLATE'                     => '',

	'AUTH_KEY'                       => 'put your unique phrase here',
	'SECURE_AUTH_KEY'                => 'put your unique phrase here',
	'LOGGED_IN_KEY'                  => 'put your unique phrase here',
	'NONCE_KEY'                      => 'put your unique phrase here',
	'AUTH_SALT'                      => 'put your unique phrase here',
	'SECURE_AUTH_SALT'               => 'put your unique phrase here',
	'LOGGED_IN_SALT'                 => 'put your unique phrase here',
	'NONCE_SALT'                     => 'put your unique phrase here',

	'FORCE_SSL_ADMIN'                => true,
	'WP_DEBUG'                       => true,
	'SCRIPT_DEBUG'                   => true,
	'SAVEQUERIES'                    => true,
	'WP_DEBUG_LOG'                   => '/tmp/php-error.log',
	'WP_DISABLE_FATAL_ERROR_HANDLER' => true,
	'JETPACK_DEV_DEBUG'              => true,
	'WP_ENVIRONMENT_TYPE'            => 'development',
);
foreach ( $constants as $constant_name => $constant_value ) {
	if ( ! defined( $constant_name ) ) {
		define( $constant_name, $constant_value );
	}
}
unset( $constants, $constant_name, $constant_value );

/* That's all, stop editing! Happy blogging. */

if ( defined( 'MULTISITE' ) && MULTISITE ) {
	// Set 'WP_SITEURL' and 'WP_CONTENT_URL' based on 'WP_HOME' on the 'ms_loaded' action hook.
	$wp_filter = array(
		'ms_loaded' => array(
			1 => array(
				'_wordpressdev_set_url_constants' => array(
					'function'      => '_wordpressdev_set_url_constants',
					'accepted_args' => 0,
				),
			),
		),
	);
} else {
	// Set 'WP_SITEURL' and 'WP_CONTENT_URL' based on 'WP_HOME'.
	_wordpressdev_set_url_constants();
}
